version: "3.9"

services:
  drone-app:
    container_name: drone-app
    networks:
      - network1
    depends_on:
      -   drone-db
    ports:
      - "${APP_PORT}:8081"
    build:
      context: .
    environment:
      DB_USERNAME: ${DB_USERNAME:?dbUserNameNorProvided}
      DB_PASSWORD: ${DB_PASSWORD:?dbPasswordNotProvided}
      DB_NAME: ${DB_NAME:?dbNameNotProvided}
      DB_HOST: drone-db
      DB_PORT: 5432
      APP_PORT: 8081
    restart: unless-stopped
  drone-db:
    container_name: drone-db
    networks:
      - network1
    image: 'postgres'
    expose:
      - 5439
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped

networks:
  network1:

